name: Connect to Server and List Files

on:
  push:
    branches:
      - main

jobs:
  connect-and-list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to server and list files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            ls -la
            cd testing/
            ls

            # Start SSH agent and add SSH key
            eval "$(ssh-agent -s)"
            expect <<EOF
            spawn ssh-add ~/.ssh/id_ed25519
            expect "Enter passphrase for /root/.ssh/id_ed25519:"
            send "${{ secrets.SSH_PASSPHRASE }}\n"
            expect eof
            EOF

            # Clone the Git repo using SSH
            expect <<EOF
            spawn git clone ${{ secrets.APP_INTERFACE }}
            expect "Enter passphrase for key '/root/.ssh/id_ed25519':"
            send "${{ secrets.SSH_PASSPHRASE }}\n"
            expect eof
            EOF