name: Connect to Server and List Files

on:
  push:
    branches:
      - main

jobs:
  connect-and-list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to server and list files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            ls -la
            cd testing/
            ls
            eval "$(ssh-agent)"
            ssh-add ~/.ssh/id_root

            # Enter the SSH passphrase after adding the SSH key to the agent
            expect <<EOF
            spawn ssh-add ~/.ssh/id_root
            expect "Enter passphrase for key '/root/.ssh/id_root':"
            send "${{ secrets.SSH_PASSPHRASE }}\n"
            expect eof
            EOF

            # Clone the Git repo using SSH
            # Pass the SSH passphrase if prompted
            eval "$(ssh-agent)"
            ssh-add ~/.ssh/id_root
            expect <<EOF
            spawn git clone ${{secrets.APP_INTERFACE}}
            expect "Enter passphrase for key '/root/.ssh/id_root':" 
            send "${{ secrets.SSH_PASSPHRASE }}\n"
            expect eof
            EOF