name: Connect to Server and List Files

on:
  push:
    branches:
      - main

jobs:
  connect-and-list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to server and list files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            ls -la
            cd testing/
            ls

            eval $(ssh-agent -s)
            ssh-add ~/.ssh/id_ed25519 <<< ${{secrets.SSH_PASSPHRASE}}
            git clone ${{secrets.APP_INTERFACE}}
            
            # # Clone the Git repo using SSH
            # # Pass the SSH passphrase if prompted
            # expect <<EOF
            # spawn git clone ${{secrets.APP_INTERFACE}}
            # expect "Enter passphrase for key '/root/.ssh/id_ed25519':" 
            # send "${{ secrets.SSH_PASSPHRASE }}\n"
            # expect eof
            # EOF