name: Connect to Server and List Files

on:
  push:
    branches:
      - main

jobs:
  connect-and-list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to server and list files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            ls -la
            cd testing/
            ls
            # eval "$(ssh-agent)"
            # ssh-add ~/.ssh/id_root

            git clone https://github.com/Netixsol/gempad-Interface.git